{% set name = "cutde" %}
{% set version = "23.6.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cutde-{{ version }}.tar.gz
  sha256: 946aeb03b3bf2f9060dabda1dd84330a67a7fddab27879010107382bcca31eac

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 3

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]

  host:
    - python
    - setuptools
    - setuptools-scm
    - wheel
    - pybind11
    - mako
    - numpy
    - pip
  run:
    - python
    - mako
    - pybind11
    - {{ pin_compatible('numpy') }}
    # Question: is this actually required, or is it optional?
    - pyproj

test:
  imports:
    - cutde
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tbenthompson/cutde
  summary: 130 million TDEs per second, Python + CUDA TDEs from Nikkhoo and Walter 2015
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
    - tbenthompson
